# Generated by Django 5.2 on 2026-03-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desciption',
            new_name='description',
        ),
    ]
